yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField('Слаг адреса', unique=True)
    description = models.TextField('Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст', help_text='Введите текст поста')
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        related_name='group_posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост комментария'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    created = models.DateTimeField('Дата комментария', auto_now_add=True)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        unique=True,
        related_name='following',
        verbose_name='Автор, на которого подписались'
    )

    def __str__(self):
        return str(self.user)

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from yatube.settings import NUM_OF_PAGES

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

User = get_user_model()


# Главная страница
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, NUM_OF_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


# Страница с постами, отфильтрованными по группам
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.group_posts.all()
    paginator = Paginator(post_list, NUM_OF_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


# Персональная страница пользователя
def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    paginator = Paginator(post_list, NUM_OF_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    ):
        following = True
    if author == request.user:
        author_is_user = True
    else:
        author_is_user = False
    context = {
        'page_obj': page_obj,
        'author': author,
        'post_list': post_list,
        'following': following,
        'author_is_user': author_is_user
    }
    return render(request, 'posts/profile.html', context)


# Подробная инфомрмация о посте
def post_detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    post_count = post.author.posts.all().count()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'post_count': post_count,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


# Создание нового поста
@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    return render(request, template, {'form': form})


# Редактирование существующего поста
@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


# Добавление комментария
@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


# Страница с постами избранных авторов
@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, NUM_OF_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


# Подписка
@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


# Отписка
@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}       
  Редактировать запись
{% else %}
  Добавить запись
{% endif %}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if form.errors %}
            {% for field in form %} 
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          {% if is_edit %}       
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
          {% if is_edit %}
            <form method="post" enctype="multipart/form-data" action="{% url "posts:post_edit" post.pk %}">
          {% else %}
            <form method="post" enctype="multipart/form-data" action="{% url "posts:post_create" %}">
          {% endif %}
            {% csrf_token %}
            {% load user_filters %}
            {% for field in form %}
              <div class="form-group row my-3" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                <div>
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}       
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}
Избранные авторы
{% endblock %}
{% block content %}
<div class="container py-5">
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% load thumbnail %}
        {% thumbnail post.image "1000" as big %}
          {% thumbnail post.image "300x300" crop="center" as small %}
            <a href="{{ big.url}}" title="look ma!"><img src="{{ small.url }}"></a>
          {% endthumbnail %}
        {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url "posts:group_list" post.group.slug %}">
        все записи группы
        </a> 
      {% endif %}
      <p>
        <a href="{% url "posts:post_detail" post.pk %}">
        детали записи
        </a>
      </p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="card-header">
    {% block header %}
    {{ group.title }}
    {% endblock %}
  </div>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% load thumbnail %}
        {% thumbnail post.image "1000" as big %}
          {% thumbnail post.image "300x300" crop="center" as small %}
            <a href="{{ big.url}}" title="look ma!"><img src="{{ small.url }}"></a>
          {% endthumbnail %}
        {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url "posts:post_detail" post.pk %}">
      детали записи
      </a>     
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
Последние обновления на сайте
{% endblock %}
{% block content %}
<div class="container py-5">
  {% include "posts/includes/switcher.html" %}
  {% load cache %}
  {% cache 20 index_page %}
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% load thumbnail %}
        {% thumbnail post.image "1000" as big %}
          {% thumbnail post.image "300x300" crop="center" as small %}
            <a href="{{ big.url}}" title="look ma!"><img src="{{ small.url }}"></a>
          {% endthumbnail %}
        {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url "posts:group_list" post.group.slug %}">
        все записи группы
        </a> 
      {% endif %}
      <p>
        <a href="{% url "posts:post_detail" post.pk %}">
        детали записи
        </a>
      </p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
  {% include "posts/includes/paginator.html" %}
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {{ post.text|truncatewords:30 }}{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %} 
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          </a> 
        </li>
        <li class="list-group-item">
          <a href="{% url "posts:group_list" post.group.slug %}">
          все записи группы
          </a> 
        </li>
      {% endif %}
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span >{{ post_count }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url "posts:profile" post.author.username %}">
        все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% load thumbnail %}
        {% thumbnail post.image "1000" as big %}
          {% thumbnail post.image "300x300" crop="center" as small %}
            <a href="{{ big.url}}" title="look ma!"><img src="{{ small.url }}"></a>
          {% endthumbnail %}
        {% endthumbnail %}
    <p>{{ post.text }}</p>
    {% if post.author == request.user %}
      <a class="btn btn-primary" href="{% url "posts:post_edit" post.pk %}">
        редактировать запись
      </a>
    {% endif %}
    {% load user_filters %}
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url "posts:add_comment" post.id %}">
          {% csrf_token %}      
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    {% for comment in post.comments.all %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.username }}
          </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
  </article>
</div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
<div class="container py-5">        
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1> 
    <h3>Всего постов: {{ post_list.count }}</h3>
    {% if not author_is_user %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url "posts:profile_unfollow" author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url "posts:profile_follow" author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% load thumbnail %}
        {% thumbnail post.image "1000" as big %}
          {% thumbnail post.image "300x300" crop="center" as small %}
            <a href="{{ big.url}}" title="look ma!"><img src="{{ small.url }}"></a>
          {% endthumbnail %}
        {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url "posts:group_list" post.group.slug %}">
        все записи группы
        </a>
      {% endif %}
      <p>  
        <a href="{% url "posts:post_detail" post.pk %}">
        детали записи
        </a>
      </p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
</div>
{% endblock %}